---
title: "Practical Machine Learning Course Project"
author: "Chris Norris"
date: "04 June 2017"
output:
  html_document: default
  pdf_document: default
---

##Background

Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement - a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. 

The goal of this project, is to predict the manner in which they did the exercise using data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. Participants were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset). 

###Data 

The training data for this project are available here: 

https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv

The test data are available here:

https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv

The data for this project come from this source: http://groupware.les.inf.puc-rio.br/har. If you use the document you create for this class for any purpose please cite them as they have been very generous in allowing their data to be used for this kind of assignment. 

###Initial Setup

```{R}
# I use Pacman now for easy package loading
install.packages("pacman", repos = "http://cran.us.r-project.org"); library(pacman)
p_load(caret, rpart, rpart.plot, randomForest, e1071, MASS)


# Set the seed for reproducability
set.seed(12321)
```

###Data Load

```{R}
URLTrain <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
URLTest <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"

training <- read.csv(URLTrain, na.strings=c("NA","#DIV/0!",""))
testing <- read.csv(URLTest, na.strings=c("NA","#DIV/0!",""))

training <- training[,!sapply(training,function(x) any(is.na(x)))]
testing <- testing[,!sapply(testing,function(x) any(is.na(x)))]
```

###Data Exploration

I've explored the data offline but here is 1 row for context for the training data set

```{R}
head(training, 1)
```

###Data Preparation

Remove columns we do not need for the exercise. Non-sensor data like Names and dates, for example, are not going to be useful here.

```{R}
training <-training[,-c(1:7)]
testing <-testing[,-c(1:7)]
```

Now we're going to split the training data set to create the validation data:

```{R}
trainingDataPartition <- createDataPartition(y=training$classe, p=0.8, list=FALSE)
trainData <- training[trainingDataPartition, ] 
validationData <- training[-trainingDataPartition, ]
```

So let's create the model and review output. 

My choice is Random Forest. Well pit 'classe' against the other variables:

```{R}
myModel.forests <- randomForest(classe ~ ., data = trainData, ntree=50)
```

50 trees was determined to be the optimal value after examination of the plot of the OOB error rate.
The graph flattens considerably after 25 trees and has a low rate of change after 40. I rounded it off to 50. The current error rate then is:

```{R}
mean(myModel.forests$err.rate)
```

Next, lets predict on the testing data and produce a confusion matrix

```{R}
predictionRF <- predict(myModel.forests, trainData, type = "class")
confRF <- confusionMatrix(predictionRF, trainData$classe)
print(confRF)
```

Excellent result. Accuracy of 1 and 95% CI > 0.99.

All looks nice and accurate. So now let's test the validation data:

```{R}
predictionRF.v <- predict(myModel.forests, validationData, type = "class")
confRF.v <- confusionMatrix(predictionRF.v, validationData$classe)
print(confRF.v)
```

Finally we can run predictions on the test data and arrive at our quiz answer:

```{R}
finalTest <- predict(myModel.forests, testing)
finalTest
```
